-- require('completion-nvim')
require('own-keymappings')
require('own-compe-extra')
vim.cmd('source ~/.local/share/nvim/site/pack/packer/opt/vim-sandwich/macros/sandwich/keymap/surround.vim')
vim.cmd('source ~/.config/nvim/vimscript/own-settings.vim')
